//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MM_Helper_in_TG.Properties.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MM_Helper_in_TG.Properties.Languages.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Box Of Fruit.
        /// </summary>
        internal static string ABoxOfFruitText {
            get {
                return ResourceManager.GetString("ABoxOfFruitText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ← Return to Menu.
        /// </summary>
        internal static string BackToMenu {
            get {
                return ResourceManager.GetString("BackToMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start banquet reminders.
        /// </summary>
        internal static string banqNotif {
            get {
                return ResourceManager.GetString("banqNotif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🛍 Banquet shop.
        /// </summary>
        internal static string BanqShop {
            get {
                return ResourceManager.GetString("BanqShop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🔔 You have started sending automatic notifications about product updates in the Banquet Shop..
        /// </summary>
        internal static string BanqStart {
            get {
                return ResourceManager.GetString("BanqStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🔕 You have stopped sending automatic notifications about product updates in the Banquet Shop..
        /// </summary>
        internal static string BanqStop {
            get {
                return ResourceManager.GetString("BanqStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bazaar Treasure.
        /// </summary>
        internal static string BazaarTreasureText {
            get {
                return ResourceManager.GetString("BazaarTreasureText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beautiful Brush.
        /// </summary>
        internal static string BeautifulBrushText {
            get {
                return ResourceManager.GetString("BeautifulBrushText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The assistant will help you in the game &apos;Merchant Master&apos; by announcing game updates and events.
        /// </summary>
        internal static string botDescription {
            get {
                return ResourceManager.GetString("botDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assistant.
        /// </summary>
        internal static string botName {
            get {
                return ResourceManager.GetString("botName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assistant is a bot helper for the game &quot;Merchant Master&quot;.
        /// </summary>
        internal static string botShortDescription {
            get {
                return ResourceManager.GetString("botShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caravan Escort.
        /// </summary>
        internal static string CaravanEscortText {
            get {
                return ResourceManager.GetString("CaravanEscortText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catch.
        /// </summary>
        internal static string CatchText {
            get {
                return ResourceManager.GetString("CatchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coin Divination.
        /// </summary>
        internal static string CoinDivinationText {
            get {
                return ResourceManager.GetString("CoinDivinationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cooking Turkey.
        /// </summary>
        internal static string CookingTurkeyText {
            get {
                return ResourceManager.GetString("CookingTurkeyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cristmas Paining.
        /// </summary>
        internal static string CristmasPainingText {
            get {
                return ResourceManager.GetString("CristmasPainingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crows Bridge.
        /// </summary>
        internal static string CrowsBridgeText {
            get {
                return ResourceManager.GetString("CrowsBridgeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decoupage.
        /// </summary>
        internal static string DecoupageText {
            get {
                return ResourceManager.GetString("DecoupageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 👘Events.
        /// </summary>
        internal static string Event {
            get {
                return ResourceManager.GetString("Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 👘Next events.
        /// </summary>
        internal static string EventNext {
            get {
                return ResourceManager.GetString("EventNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 👘The following events will be held:.
        /// </summary>
        internal static string eventNextMess {
            get {
                return ResourceManager.GetString("eventNextMess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 👘Reminder.
        /// </summary>
        internal static string EventNotif {
            get {
                return ResourceManager.GetString("EventNotif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 👘Current events.
        /// </summary>
        internal static string EventNow {
            get {
                return ResourceManager.GetString("EventNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 👘Events are currently taking place:.
        /// </summary>
        internal static string eventNowMess {
            get {
                return ResourceManager.GetString("eventNowMess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of following events.
        /// </summary>
        internal static string eventsNext {
            get {
                return ResourceManager.GetString("eventsNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start event reminders.
        /// </summary>
        internal static string eventsNotif {
            get {
                return ResourceManager.GetString("eventsNotif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of events now.
        /// </summary>
        internal static string eventsNow {
            get {
                return ResourceManager.GetString("eventsNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⛩&apos;&lt;b&gt;Feast of Lanterns&lt;/b&gt;&apos;
        ///Oh, the lantern festival will start soon. And during it, even the moon in the sky will be jealous, because it is not as bright as the lanterns on earth!.
        /// </summary>
        internal static string eventTextNext0 {
            get {
                return ResourceManager.GetString("eventTextNext0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🧶&apos;&lt;b&gt;Handmade embroidery&lt;/b&gt;&apos;
        ///Handmade embroidery is an art that preserves tradition and culture, and each stitch is a story to be told..
        /// </summary>
        internal static string eventTextNext1 {
            get {
                return ResourceManager.GetString("eventTextNext1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 👺&apos;&lt;b&gt;Pear Orchard Opera&lt;/b&gt;&apos;
        ///The Pear Orchard Opera is like a pear pie, but instead of taste, it carries culture and tradition..
        /// </summary>
        internal static string eventTextNext2 {
            get {
                return ResourceManager.GetString("eventTextNext2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🍺&apos;&lt;b&gt;Brewery&lt;/b&gt;&apos;
        ///A brewery is a place where grain turns into art and water turns into history..
        /// </summary>
        internal static string eventTextNext3 {
            get {
                return ResourceManager.GetString("eventTextNext3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🍵&apos;&lt;b&gt;The storyteller of the tea house&lt;/b&gt;&apos;
        ///Very soon, the storyteller from the tea house will come again. He always tells stories that make you sip your tea!.
        /// </summary>
        internal static string eventTextNext4 {
            get {
                return ResourceManager.GetString("eventTextNext4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🗿&apos;&lt;b&gt;Greetings of the God of Wealth&lt;/b&gt;&apos;
        ///A god of wealth is someone who always knows where to find money, but never remembers where he left his wallet!.
        /// </summary>
        internal static string eventTextNext5 {
            get {
                return ResourceManager.GetString("eventTextNext5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⛩&apos;&lt;b&gt;Feast of Lanterns&lt;/b&gt;&apos;
        ///On the festival of lanterns, even the moon in the sky will be jealous, because it is not as bright as the lanterns on earth!.
        /// </summary>
        internal static string eventTextNow0 {
            get {
                return ResourceManager.GetString("eventTextNow0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🧶&apos;&lt;b&gt;Handmade embroidery&lt;/b&gt;&apos;
        ///Handmade embroidery is an art that preserves tradition and culture, and each stitch is a story to be told..
        /// </summary>
        internal static string eventTextNow1 {
            get {
                return ResourceManager.GetString("eventTextNow1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 👺&apos;&lt;b&gt;Pear Orchard Opera&lt;/b&gt;&apos;
        ///The Pear Orchard Opera is like a pear pie, but instead of taste, it carries culture and tradition..
        /// </summary>
        internal static string eventTextNow2 {
            get {
                return ResourceManager.GetString("eventTextNow2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🍺&apos;&lt;b&gt;Brewery&lt;/b&gt;&apos;
        ///A brewery is a place where grain turns into art and water turns into history..
        /// </summary>
        internal static string eventTextNow3 {
            get {
                return ResourceManager.GetString("eventTextNow3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🍵&apos;&lt;b&gt;The storyteller of the tea house&lt;/b&gt;&apos;
        ///Oh, the storyteller from the tea house has come again. He always tells stories that make you sip your tea!.
        /// </summary>
        internal static string eventTextNow4 {
            get {
                return ResourceManager.GetString("eventTextNow4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🗿&apos;&lt;b&gt;Greetings of the God of Wealth&lt;/b&gt;&apos;
        ///A god of wealth is someone who always knows where to find money, but never remembers where he left his wallet!.
        /// </summary>
        internal static string eventTextNow5 {
            get {
                return ResourceManager.GetString("eventTextNow5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flover Tea.
        /// </summary>
        internal static string FloverTeaText {
            get {
                return ResourceManager.GetString("FloverTeaText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flower For Belover.
        /// </summary>
        internal static string FlowerForBeloverText {
            get {
                return ResourceManager.GetString("FlowerForBeloverText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🐵Great Ape Siege.
        /// </summary>
        internal static string GAS {
            get {
                return ResourceManager.GetString("GAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start GAS reminders.
        /// </summary>
        internal static string gasNotif {
            get {
                return ResourceManager.GetString("gasNotif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🔔 You have started sending automatic notifications about the start of the Great Ape Siege..
        /// </summary>
        internal static string GASStart {
            get {
                return ResourceManager.GetString("GASStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🔕 You have stopped sending automatic notifications about the start of the Great Ape Siege..
        /// </summary>
        internal static string GASStop {
            get {
                return ResourceManager.GetString("GASStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello, my name is Ba Cing,
        ///
        ///I will be your assistant in the Merchant Master game. I will inform you about the current and upcoming rankings and events, the appearance of the Great Ape Siege or Mountain Adventure, as well as the update of the assortment in the Banquet Shop. I will also tell you when the stores on Shopper Row have been updated.
        ///
        ///You can find out about all my options with the command /help.
        /// </summary>
        internal static string Greeting {
            get {
                return ResourceManager.GetString("Greeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🌸 Guild.
        /// </summary>
        internal static string Guild {
            get {
                return ResourceManager.GetString("Guild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start guild reminders.
        /// </summary>
        internal static string guildNotif {
            get {
                return ResourceManager.GetString("guildNotif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Halloween Ghost Fire.
        /// </summary>
        internal static string HalloweenGhostFireText {
            get {
                return ResourceManager.GetString("HalloweenGhostFireText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full menu.
        /// </summary>
        internal static string help {
            get {
                return ResourceManager.GetString("help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can contact me for the following commands:
        ///                    
        ////fullmenu - to call the extended menu of commands;
        ////shortmenu - to call a compact menu of commands;
        ///
        ///🥇&lt;b&gt;Ratings&lt;/b&gt;
        ///
        ////now - if you want to find out about the ratings that are happening now;
        ////next - if you want to know about the next ratings;
        ///
        ///👘&lt;b&gt;Events&lt;/b&gt;
        ///
        ////eventnow - if you want to find out about events happening now;
        ////eventnext - if you want to know about the next events;
        ///
        ///🛍&lt;b&gt;Banquet shop&lt;/b&gt;
        ///
        ////banshop - if you wan [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HelpMessText {
            get {
                return ResourceManager.GetString("HelpMessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ↑ Hide menu ↑.
        /// </summary>
        internal static string HideMenu {
            get {
                return ResourceManager.GetString("HideMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holy Tree Blessing.
        /// </summary>
        internal static string HolyTreeBlessingText {
            get {
                return ResourceManager.GetString("HolyTreeBlessingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Island Battle.
        /// </summary>
        internal static string IslandBattleText {
            get {
                return ResourceManager.GetString("IslandBattleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🐨 Mountain Adventure.
        /// </summary>
        internal static string MA {
            get {
                return ResourceManager.GetString("MA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start MA reminders.
        /// </summary>
        internal static string maNotif {
            get {
                return ResourceManager.GetString("maNotif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🔔 You have started sending automatic notifications about the start of Mountain Adventure..
        /// </summary>
        internal static string MAStart {
            get {
                return ResourceManager.GetString("MAStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master Archery.
        /// </summary>
        internal static string MasterArcheryText {
            get {
                return ResourceManager.GetString("MasterArcheryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🔕 You have stopped sending automatic notifications about the start of Mountain Adventure..
        /// </summary>
        internal static string MAStop {
            get {
                return ResourceManager.GetString("MAStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        internal static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mid-Autumn Dice Game.
        /// </summary>
        internal static string MidAutumnDiceGameText {
            get {
                return ResourceManager.GetString("MidAutumnDiceGameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monopoly Carnival.
        /// </summary>
        internal static string MonopolyCarnivalText {
            get {
                return ResourceManager.GetString("MonopolyCarnivalText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monopoly.
        /// </summary>
        internal static string MonopolyText {
            get {
                return ResourceManager.GetString("MonopolyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mooncake.
        /// </summary>
        internal static string MooncakeText {
            get {
                return ResourceManager.GetString("MooncakeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🔔 You have started sending automatic notifications about in-game events..
        /// </summary>
        internal static string NotifStart {
            get {
                return ResourceManager.GetString("NotifStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🔕 You have stopped sending automatic notifications about in-game events..
        /// </summary>
        internal static string NotifStop {
            get {
                return ResourceManager.GetString("NotifStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🥇Ratings.
        /// </summary>
        internal static string Rating {
            get {
                return ResourceManager.GetString("Rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🥇Next ratings.
        /// </summary>
        internal static string RatingNext {
            get {
                return ResourceManager.GetString("RatingNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🥇Current ratings.
        /// </summary>
        internal static string RatingNow {
            get {
                return ResourceManager.GetString("RatingNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of following ratings.
        /// </summary>
        internal static string ratingsNext {
            get {
                return ResourceManager.GetString("ratingsNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of ratings now.
        /// </summary>
        internal static string ratingsNow {
            get {
                return ResourceManager.GetString("ratingsNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🏪Shopping row&apos;s.
        /// </summary>
        internal static string ShopingRow {
            get {
                return ResourceManager.GetString("ShopingRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short menu.
        /// </summary>
        internal static string shortHelp {
            get {
                return ResourceManager.GetString("shortHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am at your service, how can I help you?
        ///You can contact me for the following commands:.
        /// </summary>
        internal static string shortMenu {
            get {
                return ResourceManager.GetString("shortMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spring Tower.
        /// </summary>
        internal static string SpringTowerText {
            get {
                return ResourceManager.GetString("SpringTowerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start SR reminders.
        /// </summary>
        internal static string srNotif {
            get {
                return ResourceManager.GetString("srNotif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swordsmith.
        /// </summary>
        internal static string SwordsmithText {
            get {
                return ResourceManager.GetString("SwordsmithText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🛍&lt;b&gt;In the Banquet Shop&lt;/b&gt; the assortment of goods has been updated.
        ///
        ///Check what&apos;s new.
        ///And don&apos;t forget to buy hammers to build your guild..
        /// </summary>
        internal static string TextBanquetShop {
            get {
                return ResourceManager.GetString("TextBanquetShop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🐵&lt;b&gt;The Siege of the Great Ape has begun!&lt;/b&gt;
        ///
        ///Don&apos;t forget to switch the main spirit between talents for efficient damage..
        /// </summary>
        internal static string TextMessageGAS {
            get {
                return ResourceManager.GetString("TextMessageGAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🐨&lt;b&gt;The Mountain Adventure has begun!&lt;/b&gt;
        ///
        ///Do not forget to calculate the damage you need to inflict..
        /// </summary>
        internal static string TextMessageMA {
            get {
                return ResourceManager.GetString("TextMessageMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🥇The following ratings will start next:
        ///
        ///💪&apos;&lt;b&gt;Battle of Talents&lt;/b&gt;&apos;
        ///During this ranking, you need to maximize the power of your talents.
        ///For this, do not forget to pump your talents and spirits.
        ///
        ///🥋&apos;&lt;b&gt;Trade War&lt;/b&gt;&apos;
        ///To get points in this rating, you need to beat the most talents of other players.
        ///Do not forget to arrange with other guild members for help..
        /// </summary>
        internal static string textRankingNext0 {
            get {
                return ResourceManager.GetString("textRankingNext0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🥇The following ratings will start next:
        ///
        ///💜&apos;&lt;b&gt;Duel of Intimacy&lt;/b&gt;&apos;
        ///In this rating, you need to increase the intimacy of loved ones with the help of gifts and costumes.
        ///Yes, the time of bags and handkerchiefs has come. Give everything.
        ///
        ///💍&apos;&lt;b&gt;Duel of children&lt;/b&gt;&apos;
        ///In this rating, you need to raise and marry children. And it doesn&apos;t matter that it is immoral and unethical..
        /// </summary>
        internal static string textRankingNext1 {
            get {
                return ResourceManager.GetString("textRankingNext1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🥇The following ratings will start next:
        ///
        ///🛕&apos;&lt;b&gt;Guild Profit Duel&lt;/b&gt;&apos;
        ///In this rating, you need to increase your profit per unit of time.
        ///Don&apos;t forget to put talents in your shops.
        ///
        ///💚&apos;&lt;b&gt;Charm Duel&lt;/b&gt;&apos;
        ///In this rating, you need to increase the charm of your loved ones with the help of gifts and costumes.
        ///Don&apos;t hesitate to give your loved one all the earrings and bracelets you&apos;ve accumulated so that she can bend over all her 358 ears and 579 hands..
        /// </summary>
        internal static string textRankingNext2 {
            get {
                return ResourceManager.GetString("textRankingNext2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🥇The following ratings will start next:
        ///
        ///🍽&apos;&lt;b&gt;Duel of Banquets&lt;/b&gt;&apos;
        ///For this ranking, you need to attend and host banquets yourself.
        ///Don&apos;t forget to talk to other guild members if you need help.
        ///
        ///💎&apos;&lt;b&gt;Ingot Match&lt;/b&gt;&apos;
        ///In this rating you need to spend ingots..
        /// </summary>
        internal static string textRankingNext3 {
            get {
                return ResourceManager.GetString("textRankingNext3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🥇The following ratings will start next:
        ///
        ///⛩&apos;&lt;b&gt;Guild Experience Duel&lt;/b&gt;&apos;
        ///To get points in this rating, you need to build a guild and destroy bosses.
        ///Don&apos;t forget to build your guild with gold hammers.
        ///
        ///💰&apos;&lt;b&gt;Profit Duel&lt;/b&gt;&apos;
        ///In this rating, you need to increase your profit per unit of time.
        ///Don&apos;t forget to put talents in your shops..
        /// </summary>
        internal static string textRankingNext4 {
            get {
                return ResourceManager.GetString("textRankingNext4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🥇The following ratings will start next:
        ///
        ///💚&apos;&lt;b&gt;Charm Duel&lt;/b&gt;&apos;
        ///In this rating, you need to increase the charm of your loved ones with the help of gifts and costumes.
        ///Don&apos;t hesitate to give your loved one all the earrings and bracelets you&apos;ve accumulated so that she can bend over all her 358 ears and 579 hands.
        ///
        ///💎&apos;&lt;b&gt;Ingot Match&lt;/b&gt;&apos;
        ///In this rating you need to spend ingots..
        /// </summary>
        internal static string textRankingNext5 {
            get {
                return ResourceManager.GetString("textRankingNext5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🥇The following ratings will start next:
        ///
        ///💒&apos;&lt;b&gt;Guild Intimacy Duel&lt;/b&gt;&apos;
        ///In this rating, you need to increase the intimacy of loved ones with the help of gifts and costumes.
        ///Yes, the time of bags and handkerchiefs has come. Give everything.
        ///
        ///💍&apos;&lt;b&gt;Duel Kids&lt;/b&gt;&apos;
        ///In this rating, you need to raise and marry children..
        /// </summary>
        internal static string textRankingNext6 {
            get {
                return ResourceManager.GetString("textRankingNext6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🥇Now the following ratings are held:
        ///
        ///💪&apos;&lt;b&gt;Battle of Talents&lt;/b&gt;&apos;
        ///During this ranking, you need to maximize the power of your talents.
        ///For this, do not forget to pump your talents and spirits.
        ///
        ///🥋&apos;&lt;b&gt;Trade War&lt;/b&gt;&apos;
        ///To get points in this rating, you need to beat the most talents of other players.
        ///Do not forget to arrange with other guild members for help..
        /// </summary>
        internal static string textRankingNow0 {
            get {
                return ResourceManager.GetString("textRankingNow0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🥇Now the following ratings are held:
        ///
        ///💜&apos;&lt;b&gt;Duel of Intimacy&lt;/b&gt;&apos;
        ///In this rating, you need to increase the intimacy of loved ones with the help of gifts and costumes.
        ///Yes, the time of bags and handkerchiefs has come. Give everything.
        ///
        ///💍&apos;&lt;b&gt;Duel of children&lt;/b&gt;&apos;
        ///In this rating, you need to raise and marry children. And it doesn&apos;t matter that it is immoral and unethical..
        /// </summary>
        internal static string textRankingNow1 {
            get {
                return ResourceManager.GetString("textRankingNow1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🥇Now the following ratings are held:
        ///
        ///🛕&apos;&lt;b&gt;Guild Profit Duel&lt;/b&gt;&apos;
        ///In this rating, you need to increase your profit per unit of time.
        ///Don&apos;t forget to put talents in your shops.
        ///
        ///💚&apos;&lt;b&gt;Charm Duel&lt;/b&gt;&apos;
        ///In this rating, you need to increase the charm of your loved ones with the help of gifts and costumes.
        ///Don&apos;t hesitate to give your loved one all the earrings and bracelets you&apos;ve accumulated so that she can bend over all her 358 ears and 579 hands..
        /// </summary>
        internal static string textRankingNow2 {
            get {
                return ResourceManager.GetString("textRankingNow2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🥇Now the following ratings are held:
        ///
        ///🍽&apos;&lt;b&gt;Duel of Banquets&lt;/b&gt;&apos;
        ///For this ranking, you need to attend and host banquets yourself.
        ///Don&apos;t forget to talk to other guild members if you need help.
        ///
        ///💎&apos;&lt;b&gt;Ingot Match&lt;/b&gt;&apos;
        ///In this rating you need to spend ingots..
        /// </summary>
        internal static string textRankingNow3 {
            get {
                return ResourceManager.GetString("textRankingNow3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🥇Now the following ratings are held:
        ///
        ///⛩&apos;&lt;b&gt;Guild Experience Duel&lt;/b&gt;&apos;
        ///To get points in this rating, you need to build a guild and destroy bosses.
        ///Don&apos;t forget to build your guild with gold hammers.
        ///
        ///💰&apos;&lt;b&gt;Profit Duel&lt;/b&gt;&apos;
        ///In this rating, you need to increase your profit per unit of time.
        ///Don&apos;t forget to put talents in your shops..
        /// </summary>
        internal static string textRankingNow4 {
            get {
                return ResourceManager.GetString("textRankingNow4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🥇Now the following ratings are held:
        ///
        ///💚&apos;&lt;b&gt;Charm Duel&lt;/b&gt;&apos;
        ///In this rating, you need to increase the charm of your loved ones with the help of gifts and costumes.
        ///Don&apos;t hesitate to give your loved one all the earrings and bracelets you&apos;ve accumulated so that she can bend over all her 358 ears and 579 hands.
        ///
        ///💎&apos;&lt;b&gt;Ingot Match&lt;/b&gt;&apos;
        ///In this rating you need to spend ingots..
        /// </summary>
        internal static string textRankingNow5 {
            get {
                return ResourceManager.GetString("textRankingNow5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🥇Now the following ratings are held:
        ///
        ///💒&apos;&lt;b&gt;Guild Intimacy Duel&lt;/b&gt;&apos;
        ///In this rating, you need to increase the intimacy of loved ones with the help of gifts and costumes.
        ///Yes, the time of bags and handkerchiefs has come. Give everything.
        ///
        ///💍&apos;&lt;b&gt;Duel Kids&lt;/b&gt;&apos;
        ///In this rating, you need to raise and marry children..
        /// </summary>
        internal static string textRankingNow6 {
            get {
                return ResourceManager.GetString("textRankingNow6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanksgiving Festival.
        /// </summary>
        internal static string ThanksgivingFestivalText {
            get {
                return ResourceManager.GetString("ThanksgivingFestivalText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Matching Game.
        /// </summary>
        internal static string TheMatchingGameText {
            get {
                return ResourceManager.GetString("TheMatchingGameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tomb Treasure.
        /// </summary>
        internal static string TombTreasureText {
            get {
                return ResourceManager.GetString("TombTreasureText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weeding Master.
        /// </summary>
        internal static string WeedingMasterText {
            get {
                return ResourceManager.GetString("WeedingMasterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wishdom Scholar.
        /// </summary>
        internal static string WishdomScholarText {
            get {
                return ResourceManager.GetString("WishdomScholarText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wonderful Melody.
        /// </summary>
        internal static string WonderfulMelodyText {
            get {
                return ResourceManager.GetString("WonderfulMelodyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World Commerce.
        /// </summary>
        internal static string WorldCommerceText {
            get {
                return ResourceManager.GetString("WorldCommerceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrap Gifts.
        /// </summary>
        internal static string WrapGiftsText {
            get {
                return ResourceManager.GetString("WrapGiftsText", resourceCulture);
            }
        }
    }
}
